flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, InputRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

class CommentForm(FlaskForm):
    comment = StringField('Comment', validators=[InputRequired()])
    submit = SubmitField('Post Comment')

flaskblog/main/routes.py
from flask import render_template, request, Blueprint
from flaskblog.models import Post

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)

@main.route('/')
@main.route('/home2')
def home_asc():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.asc()).paginate(page=page, per_page=5)
    return render_template('homeasc.html', posts=posts)


@main.route('/search', methods=['GET', 'POST'])
def search():
    s = request.args.get('s')
    if s:
        posts = Post.query.filter(Post.title.contains(s) |
        Post.content.contains(s))
    else:
        posts =  Post.query.all()
    return render_template('search.html', posts=posts)


@main.route('/about')
def about():
    return render_template('about.html', title='About')


@main.route('/privacypolicy')
def privacy_policy():
    return render_template('privacypolicy.html', title='Privacy Policy')

@main.route('/likedposts')
def liked_posts():
    return render_template('likedposts.html', title='Liked Posts')

flaskblog/posts/routes.py
from flask import (Blueprint, render_template, url_for,
flash, redirect, abort, request)
from flask_login import current_user, login_required, current_user
from flaskblog import db
from flaskblog.models import Post, Comment
from flaskblog.posts.forms import PostForm, CommentForm


posts = Blueprint('posts', __name__)

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Success! Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('make_post.html', title='New Post',form=form, legend='New Post')


@posts.route("/post/<int:post_id>", methods=['POST', 'GET'])
def post(post_id):
     post = Post.query.get_or_404(post_id)
     comments = Comment.query.filter(Comment.post_id == post.id)
     form = CommentForm()
     return render_template('post.html', title=post.title, post=post, comments=comments, form=form)

@posts.route("/post/<int:post_id>/edit", methods=['GET', 'POST'])
@login_required
def edit_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403) #Manual HTTP 403. Forbidden Route
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated', 'success')
        return redirect (url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.content.data = post.content
        form.title.data = post.title
    return render_template('make_post.html', title='Edit Post',form=form, legend='Edit Post')

@posts.route('/post/<int:post_id>/comment', methods=['GET', 'POST'])
@login_required
def post_comment(post_id):
    post = Post.query.get_or_404(post_id)
    form = CommentForm()
    if form.validate_on_submit():
        db.session.add(Comment(content=form.comment.data, post_id=post.id, author_id=current_user.id))
        db.session.commit()
        flash("Your comment has been submitted", "success")
        return redirect(f'/post/{post.id}')

        comments = Comment.query.filter(Comment.post_id == post.id)
        return render_template('post.html', post=post, comments=comments, form=form)

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted', 'success')
    return redirect (url_for('main.home'))

flaskblog/users/routes.py
from flask import render_template, Blueprint, url_for, flash, redirect, request
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('users.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_pw)
        db.session.add(user)
        db.session.commit()
        flash(f'Your account has been created. Welcome {form.username.data}!', 'success')
        return redirect(url_for('main.home'))
    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect (url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check your email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/account' , methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect (url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pictures/' + (current_user.image_file))
    return render_template('account.html', title='Account',image_file=image_file, form=form)

@users.route("/user/<string:username>")
def username_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
    .order_by(Post.date_posted.desc())\
    .paginate(page=page, per_page=5)
    return render_template('username_posts.html', posts=posts, user=user)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('users.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent to reset your password.', 'info')
        return redirect (url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('users.home'))
    user = User.verify_reset_token(token)
    if User is None:
        flash('Invalid or expired token', 'warning')
        return redirect (url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_pw
        db.session.commit()
        flash(f'Your password has been updated. You are now able to login', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
  <h1>About Page</h1>
{% endblock content %}

flaskblog/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{  image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{  current_user.username }}</h2>
          <p class="text-secondary">{{  current_user.email }}</p>
        </div>
        </div>
          <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
              <legend class="border-bottom mb-4">Account Information</legend>
              <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {% if form.username.errors %}
                  {{ form.username(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                  </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
              </div>
              <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                  {{ form.email(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                  </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
              </div>
                <div class="form-group">
                  {{ form.picture.label() }} <br>
                  {{ form.picture(class="form-control-file") }}
                  {% if form.picture.errors %}
                    {% for error in form.picture.errors %}
                        <span class="text-danger">{{ error }}</span><br>
                    {% endfor %}
                  {% endif %}
                  </div>
              </fieldset>
              <div class="form-group"> <br>
                {{ form.submit(class="btn btn-outline-info") }}
              </div>
            </form>
    </div>
{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %}
{% block content %}

    {% if current_user.is_authenticated %}
    <p>Welcome, {{  current_user.username }}!</p>
    {% else %}
    <p>Welcome, Guest!</p>
    {% endif %}

    <div class="dropdown show">
      <a class="btn btn-primary btn-sm dropdown-toggle push-right" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Sort By
      </a>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <a class="dropdown-item" href="{{ url_for('main.home_asc') }}">Sort by Ascending</a>
        <a class="dropdown-item" href="{{ url_for('main.home') }}">Sort by Descending</a>
      </div>
    </div>


   {% for post in posts.items %}
     <article class="media content-section">
       <img class="rounded-circle article-img" src="{{  url_for('static', filename='profile_pictures/' + post.author.image_file) }}">
       <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{{ url_for('users.username_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          <small class="text-muted">{{ post.date_posted.strftime('%B %d %Y') }}</small> <!-- Posts the time in Month, day, year format using datetime module -->
        </div>
        <h2><a class="article-title" href="{{  url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
        </div>
      </article>
    {% endfor %}


    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num%}
        {% if posts.page == page_num %}
          <a class = "btn btn-danger mb-3"href="{{ url_for('main.home',page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class = "btn btn-outline-danger mb-3"href="{{ url_for('main.home',page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}

  {% endblock content %}

flaskblog/templates/homeasc.html
{% extends "layout.html" %}
{% block content %}

    {% if current_user.is_authenticated %}
    <p>Welcome, {{  current_user.username }}!</p>
    {% else %}
    <p>Welcome, Guest!</p>
    {% endif %}

    <div class="dropdown show">
      <a class="btn btn-primary btn-sm dropdown-toggle push-right" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Sort By
      </a>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <a class="dropdown-item" href="{{ url_for('main.home_asc') }}">Sort by Ascending</a>
        <a class="dropdown-item" href="{{ url_for('main.home') }}">Sort by Descending</a>
      </div>
    </div>

   {% for post in posts.items %}
     <article class="media content-section">
       <img class="rounded-circle article-img" src="{{  url_for('static', filename='profile_pictures/' + post.author.image_file) }}">
       <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{{ url_for('users.username_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          <small class="text-muted">{{ post.date_posted.strftime('%B %d %Y') }}</small> <!-- Posts the time in Month, day, year format using datetime module -->
        </div>
        <h2><a class="article-title" href="{{  url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
        </div>
      </article>
    {% endfor %}

    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num%}
        {% if posts.page == page_num %}
          <a class = "btn btn-danger mb-3"href="{{ url_for('main.home_asc',page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class = "btn btn-outline-danger mb-3"href="{{ url_for('main.home_asc',page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}

  {% endblock content %}

flaskblog/templates/likedposts.html
{% extends "layout.html" %}
{% block content %}
  <h1>Liked Posts</h1>
{% endblock content %}

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Log In</legend>
      <div class="form-group">
        {{ form.email.label(class="form-control-label") }}
        {% if form.email.errors %}
          {{ form.email(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.email.errors %}
                <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
            {{ form.email(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.password.label(class="form-control-label") }}
        {% if form.password.errors %}
          {{ form.password(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.password.errors %}
                <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
            {{ form.password(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-check">
        {{ form.remember(class="form-check-input") }}
        {{ form.remember.label(class="form-check-label") }}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
    <small class="text-muted ml-1">
      <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>

    </small>
  </form>
</div>
<div class="border-top pt-3">
  <small class="text-muted">
    Need an account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign up now</a>
  </small>
</div>
{% endblock content %}

flaskblog/templates/make_post.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">{{ legend }}</legend>
      <div class="form-group">
        {{ form.title.label(class="form-control-label") }}
        {% if form.title.errors %}
          {{ form.title(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.title.errors %}
                <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
            {{ form.title(class="form-control form-control-lg") }}
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.content.label(class="form-control-label") }}
        {% if form.content.errors %}
          {{ form.content(class="form-control form-control-lg is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.content.errors %}
                <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
            {{ form.content(class="form-control form-control-lg") }}
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
   <article class="media content-section">
     <img class="rounded-circle article-img" src="{{  url_for('static', filename='profile_pictures/' + post.author.image_file) }}">
     <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.username_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%B %d %Y') }}</small> <!-- Posts the time in Month, day, year format using datetime module -->
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.edit_post', post_id=post.id) }}">Edit</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModalCenter">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
      </div>
    </article>

    <!-- Modal -->
    <div class="modal fade" id="deleteModalCenter" tabindex="-1" role="dialog" aria-labelledby="deleteModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLongTitle">Delete Post?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
              <input class="btn btn-danger" type="submit" value="Delete">
            </form>
          </div>
        </div>
      </div>
    </div>

    {% for comment in comments %}
      <p>"{{ comment.content }}" &nbsp <small>Author:
        {{ comment.user.username }}</small></p>
    {% endfor %}
    <form method="POST" action="{{ url_for('posts.post_comment', post_id=post.id) }}">
      {{ form.hidden_tag() }}
      <div class="comment-form">
        {{ form.comment.label }} {{ form.comment }}
        {% for error in form.comment.errors %}
          <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
      </div>
      <div class="border">
        {{ form.submit() }}
        </div>
      </form>
    {% for error in form.comment.errors %}
      <span style="color: red;">[{{ error }}]</span>
    {% endfor %}


    <button class="btn btn-sm btn-orange my-sm-0" type="submit">
    <i class="fas fa-thumbs-up"></i>
    </button>






  <!-- <form method="POST" action="{{ url_for('posts.post_comment', post_id=post.id) }} ">
    <div class="comment-form">
    <label for="exampleFormControlTextarea1">Say Something!</label>
    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
    <button type="button" class="btn btn-secondary btn-sm m-1" type="submit">Post Comment</button>
  </div>
  </form> -->

{% endblock content %}

flaskblog/templates/privacypolicy.html
<!--
Entirety of this page was copied from this github repo. Just a privacy policy page.
https://github.com/tomlowenthal/privacy-policy-template/blob/master/privacy-policy.html -->
{% extends "layout.html" %}
{% block content %}
<html lang=en>
 <head>
  <meta charset="utf-8" />
  <title>Flask Blog Privacy Policy</title>
   <!--Make sure to put you app name in the page title-->
  <link href="privacy-policy-updates.xml" type="application/rss+xml" title="$APPNAME Privacy Policy Updates" rel="alternate">
   <!--It's a good idea to provide an RSS feed of privacy policy updates so that users don't have to keep checking back to see if anything has changed. Especially if your feed doesn't change regularly, it doesn't take much work to update it by hand whenever you make a change. Of course, whenever you make a large change, it's still a good idea to push a notice out to your users, even if you do have an RSS feed. Make sure to remove the RSS section below if you don't use an update feed.-->
  <link rel="stylesheet" href="css/style.css" media="all" type="text/css">
  </head>
 <body>
   <header>
    <h1>Privacy Policy</h1>
    </header>

   <nav>
    <h1 id="contents">Contents</h1>
     <ul>
     <li><a href="#personal-info">Personal info</a>
      <ul><li><a href="#misc_children">Children</a></li></ul>
      </li>
     <li><a href="#collection">Collection</a>
      <ul><li><a href="#collection_tracking">Tracking technologies</a></li></ul>
      </li>
     <li><a href="#use">Use</a>
      </li>
     <li><a href="#disclosure">Disclosure</a>
      <ul>
       <li><a href="#disclosure_partners">Partners</a></li>
       <li><a href="#disclosure_legal">Legal process</a></li>
       </ul></li>

     <li><a href="#storage">Storage</a>
      <ul>
       <li><a href="#storage_location">Where your info lives</a></li>
       <li><a href="#storage_duration">How long we keep your info</a></li>
       </ul></li>

    <li><a href="#misc">About</a>
     <ul><li><a href="#choice">Your choices</a></li>
      <li><a href="#change">Changes to this policy</a></li>
      <li><a href="#contact">Contact us</a></li>
      </ul></li>

     </ul>
    </nav>

   <article>

    <nav class="to-top"><a href="#contents">back to top</a></nav>

    <section>

     <h1 id="personal-info">Personal info</h1>

      <h2 id="misc_children">Children</h2>

     </section>

    <nav class="to-top"><a href="#contents">back to top</a></nav>

    <section>

     <h1 id="collection">How we collect info</h1>

      <h2 id="collection_tracking">Tracking technologies</h2>

     </section>

    <nav class="to-top"><a href="#contents">back to top</a></nav>

    <section>

     <h1 id="use">How we use your info</h1>

     </section>

    <nav class="to-top"><a href="#contents">back to top</a></nav>

    <section>

     <h1 id="disclosure">When we share your info</h1>

      <h2 id="disclosure_partners">Our Partners</h2>

      <h2 id="disclosure_legal">Legal process</h2>

     </section>

    <nav class="to-top"><a href="#contents">back to top</a></nav>

    <section>

     <h1 id="storage">How we store your info</h1>

      <h2 id="storage_location">Where your info lives</h2>

      <h2 id="storage_duration">How long we keep your info</h2>

     </section>

    <nav class="to-top"><a href="#contents">back to top</a></nav>

    <section>

     <h1 id="misc">About</h1>

      <h2 id="misc_choice">Your choices</h2>

      <h2 id="misc_changes">Changes</h2>

      <h2 id="misc_contact">Contact us</h2>

     </section>

    </article>

  </body>

 </html>

 {% endblock content %}

flaskblog/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Join Now</legend>
          <div class="form-group">
            {{ form.username.label(class="form-control-label") }}
            {% if form.username.errors %}
              {{ form.username(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
                {{ form.username(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
              {{ form.email(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
                {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.password.label(class="form-control-label") }}
            {% if form.password.errors %}
              {{ form.password(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
                {{ form.password(class="form-control form-control-lg") }}
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.password_confirm.label(class="form-control-label") }}
            {% if form.password_confirm.errors %}
              {{ form.password_confirm(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.password_confirm.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
                {{ form.password_confirm(class="form-control form-control-lg") }}
            {% endif %}
          </div>
        </fieldset>
        <div class="form-group">
          {{ form.submit(class="btn btn-outline-info") }}
        </div>
      </form>
    </div>
    <div class="border-top pt-3">
      <small class="text-muted">
        Already have an account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
      </small>
    </div>
{% endblock content %}

flaskblog/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
  <div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Request Password</legend>
        <div class="form-group">
          {{ form.email.label(class="form-control-label") }}
          {% if form.email.errors %}
            {{ form.email(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
                  <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
              {{ form.email(class="form-control form-control-lg") }}
          {% endif %}
        </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
      </div>
    </form>
  </div>
{% endblock content %}

flaskblog/templates/search.html
{% extends "layout.html" %}
{% block content %}
  <h1>Search Page</h1>
{% endblock content %}

flaskblog/templates/username_posts.html
{% extends "layout.html" %}
{% block content %}
<h1 class="mb-4"> Posts by {{ user.username }} ({{ posts.total }})</h1>
   {% for post in posts.items %}
     <article class="media content-section">
       <img class="rounded-circle article-img" src="{{  url_for('static', filename='profile_pictures/' + post.author.image_file) }}">
       <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{{ url_for('users.username_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          <small class="text-muted">{{ post.date_posted.strftime('%B %d %Y') }}</small> <!-- Posts the time in Month, day, year format using datetime module -->
        </div>
        <h2><a class="article-title" href="{{  url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
        </div>
      </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num%}
        {% if posts.page == page_num %}
          <a class = "btn btn-danger mb-3"href="{{ url_for('users.username_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class = "btn btn-outline-danger mb-3"href="{{ url_for('users.username_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
  {% endblock content %}